In [1]:
import pandas as pd

# Dataset from the given table
data = {
    "Tid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Refund": ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"],
    "Marital Status": ["Single", "Married", "Single", "Married", "Divorced",
                       "Married", "Divorced", "Single", "Married", "Single"],
    "Taxable Income": ["125K", "100K", "70K", "120K", "95K",
                       "60K", "220K", "85K", "75K", "90K"],
    "Cheat": ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)

print("Dataset:")
display(df)

Dataset:

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

In [2]:
# Locate rows using DataFrame indexing
selected_rows = df.loc[[0, 4, 7, 8]]

print("Rows at index 0, 4, 7 and 8:")
display(selected_rows)

Rows at index 0, 4, 7 and 8:

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

In [3]:
# Q3(1): Select rows from index 3 to 7
# iloc uses positional indexing, so 3:8 is used to include row 7.
q3_1 = df.iloc[3:8]

print("Rows from index 3 to 7:")
display(q3_1)

Rows from index 3 to 7:

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

In [4]:
# Q3(2): Select rows from index 4 to 8 and columns 2 to 4
# iloc uses an exclusive stop index, so 4:9 and 2:5 are used.
q3_2 = df.iloc[4:9, 2:5]

print("Rows 4 to 8 and columns 2 to 4:")
display(q3_2)

Rows 4 to 8 and columns 2 to 4:

  Marital Status Taxable Income Cheat
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No

In [5]:
# Q3(3): Select all rows with column index 1 to 3
# Column index 3 is included by using 1:4.
q3_3 = df.iloc[:, 1:4]

print("All rows with column index 1 to 3:")
display(q3_3)

All rows with column index 1 to 3:

  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

In [6]:
# Create the employee dataset

employee_data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-06-01",
                     "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

employees_df = pd.DataFrame(employee_data)

# Convert Joining_Date from text to datetime
employees_df["Joining_Date"] = pd.to_datetime(employees_df["Joining_Date"])

# Save the sample dataset as employees.csv
employees_df.to_csv("employees.csv", index=False)

print("employees.csv created successfully.")
display(employees_df)

employees.csv created successfully.

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [7]:
# Read the employees.csv file
employees = pd.read_csv("employees.csv", parse_dates=["Joining_Date"])

print("Employee dataset:")
display(employees)

Employee dataset:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [8]:
# Shape returns (number of rows, number of columns)
print("Shape of DataFrame:", employees.shape)
print("Number of rows:", employees.shape[0])
print("Number of columns:", employees.shape[1])

Shape of DataFrame: (5, 10)
Number of rows: 5
Number of columns: 10

In [9]:
# info() displays column names, non-null counts and data types
print("Summary of the DataFrame:")
employees.info()

Summary of the DataFrame:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      str
 2   Department           5 non-null      str
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      datetime64[us]
 7   Gender               5 non-null      str
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: datetime64[us](1), float64(1), int64(5), str(3)
memory usage: 602.0 bytes

In [10]:
# Generate descriptive statistics for numerical columns
print("Descriptive statistics:")
display(employees.describe())

Descriptive statistics:

,Employee_ID,Age,Salary,Years_of_Experience,Joining_Date,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,2016-08-20 00:00:00,5500.0,4.100000
min,101.000000,28.000000,50000.00000,3.000000,2010-11-25 00:00:00,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,2013-06-01 00:00:00,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,2017-07-19 00:00:00,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,2020-03-15 00:00:00,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,2021-02-10 00:00:00,7000.0,4.700000
std,1.581139,5.612486,7905.69415,3.847077,NaN,1000.0,0.494975

In [11]:
print("First 5 rows:")
display(employees.head(5))

print("Last 3 rows:")
display(employees.tail(3))

First 5 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

Last 3 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [12]:
# i. Average salary
average_salary = employees["Salary"].mean()

# ii. Total bonus paid
total_bonus = employees["Bonus"].sum()

# iii. Youngest employee's age
youngest_age = employees["Age"].min()

# iv. Highest performance rating
highest_rating = employees["Rating"].max()

print("Average salary:", average_salary)
print("Total bonus paid:", total_bonus)
print("Youngest employee's age:", youngest_age)
print("Highest performance rating:", highest_rating)

Average salary: 60000.0
Total bonus paid: 27500
Youngest employee's age: 28
Highest performance rating: 4.7

In [13]:
# Sort employees by Salary from highest to lowest
employees_sorted = employees.sort_values(by="Salary", ascending=False)

print("Employees sorted by Salary in descending order:")
display(employees_sorted)

Employees sorted by Salary in descending order:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

In [14]:
# Categorize employees according to their performance rating
def performance_category(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

employees["Performance_Category"] = employees["Rating"].apply(performance_category)

print("DataFrame with Performance_Category:")
display(employees)

DataFrame with Performance_Category:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [15]:
# Check the number of missing values in every column
print("Missing values in each column:")
display(employees.isnull().sum())

# Check whether the entire DataFrame contains any missing value
print("Total missing values:", employees.isnull().sum().sum())

Missing values in each column:

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

Total missing values: 0

In [16]:
# Rename Employee_ID column to ID
employees.rename(columns={"Employee_ID": "ID"}, inplace=True)

print("DataFrame after renaming Employee_ID to ID:")
display(employees)

DataFrame after renaming Employee_ID to ID:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [17]:
# i. Employees with more than 5 years of experience
experienced_employees = employees[employees["Years_of_Experience"] > 5]

print("Employees with more than 5 years of experience:")
display(experienced_employees)

# ii. Employees belonging to the IT department
it_employees = employees[employees["Department"] == "IT"]

print("Employees belonging to the IT department:")
display(it_employees)

Employees with more than 5 years of experience:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

Employees belonging to the IT department:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

In [18]:
# Tax is 10% of the Salary
employees["Tax"] = employees["Salary"] * 0.10

print("DataFrame after adding Tax:")
display(employees)

DataFrame after adding Tax:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

In [19]:
# Save the final modified DataFrame
employees.to_csv("employees_modified.csv", index=False)

print("Modified DataFrame saved successfully as employees_modified.csv")

Modified DataFrame saved successfully as employees_modified.csv

In [20]:
 # Q4: Read the Iris CSV file
# Keep Iris.csv in the same folder as this notebook.

iris_df = pd.read_csv("Iris.csv")

print("First five rows of the Iris dataset:")
display(iris_df.head())

First five rows of the Iris dataset:

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [21]:
# Make a copy so the original Iris DataFrame remains unchanged
iris_modified = iris_df.copy()

# Delete row at index 4
iris_modified = iris_modified.drop(index=4)

# Delete column at positional index 3
column_to_delete = iris_modified.columns[3]
iris_modified = iris_modified.drop(columns=column_to_delete)

print("Iris dataset after deleting row 4 and column 3:")
display(iris_modified)

Iris dataset after deleting row 4 and column 3:

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
5      6            5.4           3.9           0.4     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[149 rows x 5 columns]